// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
	"time"
)

type Balance struct {
	Name      string     `json:"name"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Priority  *big.Int   `json:"priority,omitempty"`
}

func (b Balance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Balance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Balance) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Balance) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *Balance) GetPriority() *big.Int {
	if o == nil {
		return nil
	}
	return o.Priority
}
