// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
	"time"
)

// BalanceWithAssets - A named balance within a wallet together with the amounts it holds per asset
type BalanceWithAssets struct {
	// Name of the balance within the wallet
	Name string `json:"name"`
	// When the funds in this balance expire. Expired funds stop counting towards available funds
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Ordering hint when choosing which balances to debit first. Lower values are debited first, and it only breaks ties between balances that carry no expiry date
	Priority *big.Int `json:"priority,omitempty"`
	// Amounts held, keyed by asset
	Assets map[string]*big.Int `json:"assets"`
}

func (b BalanceWithAssets) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BalanceWithAssets) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BalanceWithAssets) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *BalanceWithAssets) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *BalanceWithAssets) GetPriority() *big.Int {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *BalanceWithAssets) GetAssets() map[string]*big.Int {
	if o == nil {
		return map[string]*big.Int{}
	}
	return o.Assets
}
