// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
	"time"
)

// Balance - A named balance within a wallet, optionally carrying an expiry date
type Balance struct {
	// Name of the balance within the wallet
	Name string `json:"name"`
	// When the funds in this balance expire. Expired funds stop counting towards available funds
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Ordering hint when choosing which balances to debit first. Lower values are debited first, and it only breaks ties between balances that carry no expiry date
	Priority *big.Int `json:"priority,omitempty"`
}

func (b Balance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Balance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Balance) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Balance) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *Balance) GetPriority() *big.Int {
	if o == nil {
		return nil
	}
	return o.Priority
}
