// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateBalanceResponse struct {
	// A named balance within a wallet, optionally carrying an expiry date
	Data Balance `json:"data"`
}

func (o *CreateBalanceResponse) GetData() Balance {
	if o == nil {
		return Balance{}
	}
	return o.Data
}
