// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
	"time"
)

type CreateBalanceRequest struct {
	Name      string     `json:"name"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Priority  *big.Int   `json:"priority,omitempty"`
}

func (c CreateBalanceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBalanceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateBalanceRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateBalanceRequest) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *CreateBalanceRequest) GetPriority() *big.Int {
	if o == nil {
		return nil
	}
	return o.Priority
}
