// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateWalletResponse struct {
	// A wallet backed by a set of ledger accounts
	Data Wallet `json:"data"`
}

func (o *CreateWalletResponse) GetData() Wallet {
	if o == nil {
		return Wallet{}
	}
	return o.Data
}
