// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DebitWalletResponse struct {
	// Funds locked by a pending debit, later either confirmed or voided
	Data Hold `json:"data"`
}

func (o *DebitWalletResponse) GetData() Hold {
	if o == nil {
		return Hold{}
	}
	return o.Data
}
