// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetBalanceResponse struct {
	// A named balance within a wallet together with the amounts it holds per asset
	Data BalanceWithAssets `json:"data"`
}

func (o *GetBalanceResponse) GetData() BalanceWithAssets {
	if o == nil {
		return BalanceWithAssets{}
	}
	return o.Data
}
