// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetHoldsResponseCursor - Paginated cursor wrapping the list of holds
type GetHoldsResponseCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore *bool `json:"hasMore,omitempty"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string `json:"next,omitempty"`
	Data []Hold  `json:"data"`
}

func (o *GetHoldsResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *GetHoldsResponseCursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *GetHoldsResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *GetHoldsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GetHoldsResponseCursor) GetData() []Hold {
	if o == nil {
		return []Hold{}
	}
	return o.Data
}

type GetHoldsResponse struct {
	// Paginated cursor wrapping the list of holds
	Cursor GetHoldsResponseCursor `json:"cursor"`
}

func (o *GetHoldsResponse) GetCursor() GetHoldsResponseCursor {
	if o == nil {
		return GetHoldsResponseCursor{}
	}
	return o.Cursor
}
