// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetHoldResponse struct {
	// A hold together with the amounts it currently locks and has already released
	Data ExpandedDebitHold `json:"data"`
}

func (o *GetHoldResponse) GetData() ExpandedDebitHold {
	if o == nil {
		return ExpandedDebitHold{}
	}
	return o.Data
}
