// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Cursor - Paginated cursor wrapping the list of transactions
type Cursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore *bool `json:"hasMore,omitempty"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string       `json:"next,omitempty"`
	Data []Transaction `json:"data"`
}

func (o *Cursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *Cursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *Cursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *Cursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *Cursor) GetData() []Transaction {
	if o == nil {
		return []Transaction{}
	}
	return o.Data
}

type GetTransactionsResponse struct {
	// Paginated cursor wrapping the list of transactions
	Cursor Cursor `json:"cursor"`
}

func (o *GetTransactionsResponse) GetCursor() Cursor {
	if o == nil {
		return Cursor{}
	}
	return o.Cursor
}
