// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWalletResponse struct {
	// A wallet together with the funds it currently holds
	Data WalletWithBalances `json:"data"`
}

func (o *GetWalletResponse) GetData() WalletWithBalances {
	if o == nil {
		return WalletWithBalances{}
	}
	return o.Data
}
