// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWalletSummaryResponse struct {
	// Aggregated funds held by a wallet, broken down by availability
	Data WalletSummary `json:"data"`
}

func (o *GetWalletSummaryResponse) GetData() WalletSummary {
	if o == nil {
		return WalletSummary{}
	}
	return o.Data
}
