// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Hold - Funds locked by a pending debit, later either confirmed or voided
type Hold struct {
	// The unique ID of the hold.
	ID string `json:"id"`
	// The ID of the wallet the hold is associated with.
	WalletID string `json:"walletID"`
	// Metadata associated with the hold.
	Metadata map[string]string `json:"metadata"`
	// Asset the held funds are denominated in
	Asset string `json:"asset"`
	// Human-readable reason the funds were held
	Description string `json:"description"`
	// The counterparty of a wallet movement, either a ledger account or another wallet
	Destination *Subject `json:"destination,omitempty"`
}

func (o *Hold) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Hold) GetWalletID() string {
	if o == nil {
		return ""
	}
	return o.WalletID
}

func (o *Hold) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *Hold) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Hold) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Hold) GetDestination() *Subject {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *Hold) GetDestinationAccount() *LedgerAccountSubject {
	if v := o.GetDestination(); v != nil {
		return v.LedgerAccountSubject
	}
	return nil
}

func (o *Hold) GetDestinationWallet() *WalletSubject {
	if v := o.GetDestination(); v != nil {
		return v.WalletSubject
	}
	return nil
}
