// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LedgerAccountSubject struct {
	// Discriminator identifying this subject as a ledger account
	Type string `json:"type"`
	// Address of the ledger account
	Identifier string `json:"identifier"`
}

func (o *LedgerAccountSubject) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *LedgerAccountSubject) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}
