// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListWalletsResponseCursor - Paginated cursor wrapping the list of wallets
type ListWalletsResponseCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore *bool `json:"hasMore,omitempty"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string  `json:"next,omitempty"`
	Data []Wallet `json:"data"`
}

func (o *ListWalletsResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *ListWalletsResponseCursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *ListWalletsResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListWalletsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListWalletsResponseCursor) GetData() []Wallet {
	if o == nil {
		return []Wallet{}
	}
	return o.Data
}

type ListWalletsResponse struct {
	// Paginated cursor wrapping the list of wallets
	Cursor ListWalletsResponseCursor `json:"cursor"`
}

func (o *ListWalletsResponse) GetCursor() ListWalletsResponseCursor {
	if o == nil {
		return ListWalletsResponseCursor{}
	}
	return o.Cursor
}
