// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListWalletsResponseCursor struct {
	PageSize int64    `json:"pageSize"`
	HasMore  *bool    `json:"hasMore,omitempty"`
	Previous *string  `json:"previous,omitempty"`
	Next     *string  `json:"next,omitempty"`
	Data     []Wallet `json:"data"`
}

func (o *ListWalletsResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *ListWalletsResponseCursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *ListWalletsResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListWalletsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListWalletsResponseCursor) GetData() []Wallet {
	if o == nil {
		return []Wallet{}
	}
	return o.Data
}

type ListWalletsResponse struct {
	Cursor ListWalletsResponseCursor `json:"cursor"`
}

func (o *ListWalletsResponse) GetCursor() ListWalletsResponseCursor {
	if o == nil {
		return ListWalletsResponseCursor{}
	}
	return o.Cursor
}
