// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListBalancesResponseCursor - Paginated cursor wrapping the list of balances
type ListBalancesResponseCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore *bool `json:"hasMore,omitempty"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string   `json:"next,omitempty"`
	Data []Balance `json:"data"`
}

func (o *ListBalancesResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *ListBalancesResponseCursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *ListBalancesResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListBalancesResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListBalancesResponseCursor) GetData() []Balance {
	if o == nil {
		return []Balance{}
	}
	return o.Data
}

type ListBalancesResponse struct {
	// Paginated cursor wrapping the list of balances
	Cursor ListBalancesResponseCursor `json:"cursor"`
}

func (o *ListBalancesResponse) GetCursor() ListBalancesResponseCursor {
	if o == nil {
		return ListBalancesResponseCursor{}
	}
	return o.Cursor
}
