// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
)

type Monetary struct {
	// The asset of the monetary value.
	Asset string `json:"asset"`
	// The amount of the monetary value.
	Amount *big.Int `json:"amount"`
}

func (m Monetary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Monetary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Monetary) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Monetary) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}
