// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
)

type Posting struct {
	// Amount to move, as an arbitrary-precision integer expressed in the asset's smallest unit
	Amount *big.Int `json:"amount"`
	// The asset being moved, optionally carrying a scale suffix such as USD/2
	Asset string `json:"asset"`
	// Address of the account credited by this posting
	Destination string `json:"destination"`
	// Address of the account debited by this posting
	Source string `json:"source"`
}

func (p Posting) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Posting) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Posting) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *Posting) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Posting) GetDestination() string {
	if o == nil {
		return ""
	}
	return o.Destination
}

func (o *Posting) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}
