// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"time"
)

type Transaction struct {
	// Name of the ledger the transaction was recorded in
	Ledger *string `json:"ledger,omitempty"`
	// The transaction time: when the transaction is considered to have occurred. See [bi- temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp time.Time `json:"timestamp"`
	// The fund movements making up the transaction
	Postings []Posting `json:"postings"`
	// Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
	Reference *string `json:"reference,omitempty"`
	// Metadata associated with the wallet.
	Metadata map[string]string `json:"metadata"`
	// Unique sequential identifier for this transaction within the ledger
	ID int64 `json:"id"`
	// Volumes aggregated per account and per asset
	PreCommitVolumes map[string]map[string]Volume `json:"preCommitVolumes,omitempty"`
	// Volumes aggregated per account and per asset
	PostCommitVolumes map[string]map[string]Volume `json:"postCommitVolumes,omitempty"`
}

func (t Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Transaction) GetLedger() *string {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *Transaction) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}

func (o *Transaction) GetPostings() []Posting {
	if o == nil {
		return []Posting{}
	}
	return o.Postings
}

func (o *Transaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *Transaction) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *Transaction) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Transaction) GetPreCommitVolumes() map[string]map[string]Volume {
	if o == nil {
		return nil
	}
	return o.PreCommitVolumes
}

func (o *Transaction) GetPostCommitVolumes() map[string]map[string]Volume {
	if o == nil {
		return nil
	}
	return o.PostCommitVolumes
}
