// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WalletSubject struct {
	Type       string  `json:"type"`
	Identifier string  `json:"identifier"`
	Balance    *string `json:"balance,omitempty"`
}

func (o *WalletSubject) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *WalletSubject) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *WalletSubject) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}
