// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/wallets/pkg/client/internal/utils"
	"math/big"
)

// WalletSummary - Aggregated funds held by a wallet, broken down by availability
type WalletSummary struct {
	// Each balance of the wallet with its per-asset amounts
	Balances []BalanceWithAssets `json:"balances"`
	// Funds available to debit, keyed by asset. Covers balances with no expiry and those not yet expired
	AvailableFunds map[string]*big.Int `json:"availableFunds"`
	// Funds held in balances whose expiry date has passed, keyed by asset
	ExpiredFunds map[string]*big.Int `json:"expiredFunds"`
	// Funds held in balances carrying an expiry date that has not yet passed, keyed by asset
	ExpirableFunds map[string]*big.Int `json:"expirableFunds"`
	// Funds currently locked by pending holds, keyed by asset
	HoldFunds map[string]*big.Int `json:"holdFunds"`
}

func (w WalletSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WalletSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WalletSummary) GetBalances() []BalanceWithAssets {
	if o == nil {
		return []BalanceWithAssets{}
	}
	return o.Balances
}

func (o *WalletSummary) GetAvailableFunds() map[string]*big.Int {
	if o == nil {
		return map[string]*big.Int{}
	}
	return o.AvailableFunds
}

func (o *WalletSummary) GetExpiredFunds() map[string]*big.Int {
	if o == nil {
		return map[string]*big.Int{}
	}
	return o.ExpiredFunds
}

func (o *WalletSummary) GetExpirableFunds() map[string]*big.Int {
	if o == nil {
		return map[string]*big.Int{}
	}
	return o.ExpirableFunds
}

func (o *WalletSummary) GetHoldFunds() map[string]*big.Int {
	if o == nil {
		return map[string]*big.Int{}
	}
	return o.HoldFunds
}
