// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type ConfirmHoldRequest struct {
	HoldID string `pathParam:"style=simple,explode=false,name=hold_id"`
	// Use an idempotency key
	IdempotencyKey     *string                        `header:"style=simple,explode=false,name=Idempotency-Key"`
	ConfirmHoldRequest *components.ConfirmHoldRequest `request:"mediaType=application/json"`
}

func (o *ConfirmHoldRequest) GetHoldID() string {
	if o == nil {
		return ""
	}
	return o.HoldID
}

func (o *ConfirmHoldRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *ConfirmHoldRequest) GetConfirmHoldRequest() *components.ConfirmHoldRequest {
	if o == nil {
		return nil
	}
	return o.ConfirmHoldRequest
}

type ConfirmHoldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *ConfirmHoldResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ConfirmHoldResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
