// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type CreateBalanceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Use an idempotency key
	IdempotencyKey       *string                          `header:"style=simple,explode=false,name=Idempotency-Key"`
	CreateBalanceRequest *components.CreateBalanceRequest `request:"mediaType=application/json"`
}

func (o *CreateBalanceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateBalanceRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *CreateBalanceRequest) GetCreateBalanceRequest() *components.CreateBalanceRequest {
	if o == nil {
		return nil
	}
	return o.CreateBalanceRequest
}

type CreateBalanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created balance
	CreateBalanceResponse *components.CreateBalanceResponse
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *CreateBalanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateBalanceResponse) GetCreateBalanceResponse() *components.CreateBalanceResponse {
	if o == nil {
		return nil
	}
	return o.CreateBalanceResponse
}

func (o *CreateBalanceResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
