// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type CreateWalletRequest struct {
	// Use an idempotency key
	IdempotencyKey      *string                         `header:"style=simple,explode=false,name=Idempotency-Key"`
	CreateWalletRequest *components.CreateWalletRequest `request:"mediaType=application/json"`
}

func (o *CreateWalletRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *CreateWalletRequest) GetCreateWalletRequest() *components.CreateWalletRequest {
	if o == nil {
		return nil
	}
	return o.CreateWalletRequest
}

type CreateWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Wallet created
	CreateWalletResponse *components.CreateWalletResponse
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *CreateWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateWalletResponse) GetCreateWalletResponse() *components.CreateWalletResponse {
	if o == nil {
		return nil
	}
	return o.CreateWalletResponse
}

func (o *CreateWalletResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
