// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type CreditWalletRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Use an idempotency key
	IdempotencyKey      *string                         `header:"style=simple,explode=false,name=Idempotency-Key"`
	CreditWalletRequest *components.CreditWalletRequest `request:"mediaType=application/json"`
}

func (o *CreditWalletRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreditWalletRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *CreditWalletRequest) GetCreditWalletRequest() *components.CreditWalletRequest {
	if o == nil {
		return nil
	}
	return o.CreditWalletRequest
}

type CreditWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *CreditWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreditWalletResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
