// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type GetBalanceRequest struct {
	ID          string `pathParam:"style=simple,explode=false,name=id"`
	BalanceName string `pathParam:"style=simple,explode=false,name=balanceName"`
}

func (o *GetBalanceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetBalanceRequest) GetBalanceName() string {
	if o == nil {
		return ""
	}
	return o.BalanceName
}

type GetBalanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Balance summary
	GetBalanceResponse *components.GetBalanceResponse
}

func (o *GetBalanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBalanceResponse) GetGetBalanceResponse() *components.GetBalanceResponse {
	if o == nil {
		return nil
	}
	return o.GetBalanceResponse
}
