// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetHoldRequest struct {
	// The hold ID
	HoldID string `pathParam:"style=simple,explode=false,name=holdID"`
}

func (o *GetHoldRequest) GetHoldID() string {
	if o == nil {
		return ""
	}
	return o.HoldID
}

type GetHoldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Holds
	GetHoldResponse *components.GetHoldResponse
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *GetHoldResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHoldResponse) GetGetHoldResponse() *components.GetHoldResponse {
	if o == nil {
		return nil
	}
	return o.GetHoldResponse
}

func (o *GetHoldResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
