// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type GetHoldRequest struct {
	// The hold ID
	HoldID string `pathParam:"style=simple,explode=false,name=holdID"`
}

func (o *GetHoldRequest) GetHoldID() string {
	if o == nil {
		return ""
	}
	return o.HoldID
}

type GetHoldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Holds
	GetHoldResponse *components.GetHoldResponse
}

func (o *GetHoldResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHoldResponse) GetGetHoldResponse() *components.GetHoldResponse {
	if o == nil {
		return nil
	}
	return o.GetHoldResponse
}
