// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type GetWalletRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetWalletRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Wallet
	GetWalletResponse *components.GetWalletResponse
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *GetWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWalletResponse) GetGetWalletResponse() *components.GetWalletResponse {
	if o == nil {
		return nil
	}
	return o.GetWalletResponse
}

func (o *GetWalletResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
