// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type GetWalletSummaryRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetWalletSummaryRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetWalletSummaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Wallet summary
	GetWalletSummaryResponse *components.GetWalletSummaryResponse
}

func (o *GetWalletSummaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWalletSummaryResponse) GetGetWalletSummaryResponse() *components.GetWalletSummaryResponse {
	if o == nil {
		return nil
	}
	return o.GetWalletSummaryResponse
}
