// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/wallets/pkg/client/models/components"
)

type ListBalancesRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ListBalancesRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ListBalancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Balances list
	ListBalancesResponse *components.ListBalancesResponse
}

func (o *ListBalancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListBalancesResponse) GetListBalancesResponse() *components.ListBalancesResponse {
	if o == nil {
		return nil
	}
	return o.ListBalancesResponse
}
