// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type UpdateWalletRequestBody struct {
	// Custom metadata to attach to this wallet.
	Metadata map[string]string `json:"metadata"`
}

func (o *UpdateWalletRequestBody) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

type UpdateWalletRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Use an idempotency key
	IdempotencyKey *string                  `header:"style=simple,explode=false,name=Idempotency-Key"`
	RequestBody    *UpdateWalletRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateWalletRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateWalletRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *UpdateWalletRequest) GetRequestBody() *UpdateWalletRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type UpdateWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorResponse *components.ErrorResponse
}

func (o *UpdateWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateWalletResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
