// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

type Wallets struct {
	V1 *V1

	sdkConfiguration sdkConfiguration
}

func newWallets(sdkConfig sdkConfiguration) *Wallets {
	return &Wallets{
		sdkConfiguration: sdkConfig,
		V1:               newV1(sdkConfig),
	}
}
